<html>
<head>
    <style>
        table, th, td {border: 1px solid black;}
    </style>
</head>
<body>
<h1>Bee Safe Neighborhood: $neighborhood$</h1>
<table style="border: 0px; width: 900px"><tr><td style="border: 0px"><h2>Block: $block$</h2></td><td style="border: 0px"><h2>Captain: $captain$</h2></td></tr></table>

<div style="text-align: center;"><img src="$image_path$"></div>

<p>As bees are endangered by the use of neonicotinoids and other systemic pesticides in the environment, and I am aware of these dangers, I pledge to help reduce the amount of these poisons in the environment by adhering to the level or levels of care described below.</p>

<ul>
<li>Level 1 (most important): I will not use neonicotinoids or other systemics, and I will not use or buy soils, seeds, or plants that have been treated with neonicotinoids or other systemics.</li>
<li>Level 2: I will not use any poisonous products outdoors.</li>
<li>Level 3: I will not use any poisons outdoors, and I will plant and raise plants that provide the pollen and nectar that bees and other pollinators need.</li>
</ul>
$row_page$
</body>
</html>