<div style="page-break-after:always;">
<table style="width: 1200px">
        <thead style="text-align: center; background-color: lightgray; font-weight: bold"><td style="width:20%">Address</td><td style="width:20%">Name</td><td style="width:25%">Email</td><td style="width:10%">Yes/No/Maybe</td><td style="width:5%">Level</td><td style="width:10%">Not Home</td><td style="width:10%">Return Date</td></thead>
    $row$
</table>
</div>